<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="ErrorOr" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.Net.Client" />
		<PackageReference Include="Grpc.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MediatR" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\error.proto" GrpcServices="None" />
	</ItemGroup>

</Project>
